general {
    lock_cmd = /home/tumbleweed/dotfiles/.config/scripts/hyprlock.sh
    before_sleep_cmd = hyprlock
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300
    on-timeout = /home/tumbleweed/dotfiles/.config/scripts/hyprlock.sh
    on-resume = echo "Unlocked"
}
